executable            = /afs/cern.ch/user/d/daocampo/public/jetClassiferEfficiencywithGNN/condor/extract_TTTo2L2Nu.sh
arguments             = $(ClusterId)$(ProcId)
output                = /afs/cern.ch/user/d/daocampo/public/jetClassiferEfficiencywithGNN/condor/logs/extract_TTTo2L2Nu.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/d/daocampo/public/jetClassiferEfficiencywithGNN/condor/logs/extract_TTTo2L2Nu.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/d/daocampo/public/jetClassiferEfficiencywithGNN/condor/logs/extract_TTTo2L2Nu.$(ClusterId).$(ProcId).log

+JobFlavour           = tomorrow
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/daocampo/gnn_test:latest"
queue 1
